apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sstore
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.vault_url }}
      serviceAccountRef:
        name: todo
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esecret
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: sstore
  target:
    name: esecrets
    creationPolicy: Owner
  data:
  - secretKey: db_password
    remoteRef:
      key: sql1-db-pass
