apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}
spec:
  selector:
    {{- include "todo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
